[green_agent]
agentbeats_id = "019bc5a4-101d-7e73-a9cc-9dc5aaaa65b1"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[[participants]]
agentbeats_id = ""
name = "agent"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[config]
domain = "airline"
task_ids = ["0", "1"]
user_llm = "openai/gpt-4o-mini" 